config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    authenticated :user do
      root 'sayings#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :sayings do
    resources :words
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/saying.rb
class Saying < ApplicationRecord
  has_many :words, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :saying
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sayings_controller.rb
class SayingsController < ApplicationController
  before_action :set_saying, only: [:show, :edit, :update, :destroy]

  # GET /sayings
  # GET /sayings.json
  def index
    @sayings = Saying.all
  end

  # GET /sayings/1
  # GET /sayings/1.json
  def show
  end

  # GET /sayings/new
  def new
    @saying = Saying.new
    @saying.words.build
  end

  # GET /sayings/1/edit
  def edit
  end

  # POST /sayings
  # POST /sayings.json
  def create
    @saying = Saying.new

    respond_to do |format|
      if @saying.save
        format.html { redirect_to new_saying_word_path(@saying), notice: 'Saying was successfully created.' }
        format.json { render :show, status: :created, location: new_saying_word_path(@saying)}
      else
        format.html { render :new }
        format.json { render json: @saying.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sayings/1
  # PATCH/PUT /sayings/1.json
  def update
    respond_to do |format|
      if @saying.update
        format.html { redirect_to @saying, notice: 'Saying was successfully updated.' }
        format.json { render :show, status: :ok, location: @saying }
      else
        format.html { render :edit }
        format.json { render json: @saying.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sayings/1
  # DELETE /sayings/1.json
  def destroy
    @saying.destroy
    respond_to do |format|
      format.html { redirect_to sayings_url, notice: 'Saying was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saying
      @saying = Saying.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @saying = Saying.find(params[:saying_id])
    @words = @saying.words
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @saying = Saying.find(params[:saying_id])
    @word = @saying.words.build(params[:word])
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @saying = Saying.find(params[:saying_id])
    @word = @saying.words.build(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to sayings_path, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @saying }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to sayings_path, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @saying }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to sayings_path, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @saying = Saying.find(params[:saying_id])
      @word = @saying.words.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:user_word, :user_name, :saying_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sayings_helper.rb
module SayingsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sayings generator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <!-- Navigation -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                  </button>
                  <%= link_to "Home", sayings_path, class: "navbar-brand" %>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="float:center">
                  <ul class="nav navbar-nav" >
                    <%- if current_user %>
                    <li>
                      <%= link_to 'New Saying', { :controller => "sayings", :action => "create"}, :method => :post %>
                    </li>
                    <li>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
                    </li>
                    <%- else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li style="float:right">
                      <%= link_to "Register", new_user_registration_path %>
                    </li>
                    <% end %>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
      </nav>

      <!-- Page Content -->
      <div class="container">

          <div class="row">
              <div class="col-lg-12 text-center">
                <% flash.each do |a, b| %>
                  <div class="alert alert-success"> <%= b %> </div>
                  <% end %>
                  <%= yield %>
              </div>
          </div>
          <!-- /.row -->
      </div>
      <!-- /.container -->
      <style>body{padding-top:70px;}</style>
  </body>

</html>

app/views/sayings/_form.html.erb
<%= form_for(saying) do |f| %>
  <% if saying.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saying.errors.count, "error") %> prohibited this saying from being saved:</h2>

      <ul>
      <% saying.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sayings/edit.html.erb
<h1>Editing Saying</h1>

<%= render 'form', saying: @saying %>

<%= link_to 'Show', @saying %> |
<%= link_to 'Back', sayings_path %>

app/views/sayings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sayings</h1>
<% @sayings.each do |saying| %>
  <center>
    <table>
      <center>
      <thead>
        <tr>
          <th><center>Text</center></th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>
              <b>
                <% saying.words.each do |word| %>
                  <%= word.user_word + " " %>
                <% end %>
              </b>
            </td>
            <%- if current_user %>
              <%- if current_user.username != saying.words.last.user_name %>
                <td><%= link_to 'New Word', new_saying_word_path(saying) %></td>
              <% end %>
            <% end %>
            <td><%= link_to 'Show', saying %></td>
            <td><%= link_to 'Destroy', saying, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      </tbody>
      <br>
    </table>
  </center>
  <br>
  <center>
    <table>
      <thead>
        <tr>
          <th><center>User word</center></th>
          <th><center>User name</center></th>
          <th><center>Created at</center></th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% saying.words.each do |word| %>
          <tr>
            <td><b><%= word.user_word %></b></td>
            <td><%= word.user_name %></td>
            <td><%= word.created_at %></td>
            <%= form_for([saying, word]) do |f| %>
              <td><%= f.text_field :user_word, :required => true, :pattern => '[^ \f\n\r\t\v.]+'%></td>
              <td><%= f.text_field :user_name, :value => current_user.username, :readonly => true %></td>
              <td><%= f.submit %></td>
            <% end %>
            <td><%= link_to 'Destroy', polymorphic_url([saying, word]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </center>
  <br>
<% end %>
<br>

app/views/sayings/new.html.erb
<h1>New Saying</h1>

<%= render 'form', saying: @saying %>

<%= link_to 'Back', sayings_path %>

app/views/sayings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <% @saying.words.each do |word| %>
    <%= word.user_word + " " %>
    <% end %>
</p>
<br>
<center>
<table>
  <thead>
    <tr>
      <th><center>User word</center></th>
      <th><center>User name</center></th>
      <th><center>Created at</center></th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @saying.words.each do |word| %>
      <tr>
        <td><b><%= word.user_word %></b></td>
        <td><%= word.user_name %></td>
        <td><%= word.created_at %></td>
        <td><%= link_to 'Edit', edit_saying_word_path(@saying, word) %></td>
        <td><%= link_to 'Destroy', polymorphic_url([@saying, word]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<%= link_to 'Back', sayings_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/words/_form.html.erb
<%= form_for([@saying, @word]) do |f| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_word %>
    <%= f.text_field :user_word, :required => true, :pattern => '[^ \f\n\r\t\v.]+'%>
  </div>

  <div class="field">
    <%= f.label :user_name %>
    <%= f.text_field :user_name, :value => current_user.username, :readonly => true %>
  </div>

  <div class="field">
    <%= f.label :saying_id %>
    <%= f.text_field :saying_id, :readonly => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back to saying', @saying %> |
<%= link_to 'Back', saying_words_path(@saying) %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>User word</th>
      <th>User name</th>
      <th>Saying id</th>
      <th>Created at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.user_word %></td>
        <td><%= word.user_name %></td>
        <td><%= word.saying_id %></td>
        <td><%= word.created_at %></td>
        <td><%= link_to 'Edit', edit_saying_word_path(@saying, word) %></td>
        <td><%= link_to 'Destroy', polymorphic_url([@saying, word]), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Word', new_saying_word_path(@saying) %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', saying_words_path(@saying) %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User word:</strong>
  <%= @word.user_word %>
</p>

<p>
  <strong>User name:</strong>
  <%= @word.user_name %>
</p>

<p>
  <strong>Saying:</strong>
  <%= @word.saying %>
</p>

<%= link_to 'Edit', edit_word_path(@saying,@word) %> |
<%= link_to 'Back', saying_words_path(@saying) %>